alter table MEDICALRECORD_CONSULTATION_RECORD add column CREATION_INFO_DATE_ timestamp ^
update MEDICALRECORD_CONSULTATION_RECORD set CREATION_INFO_DATE_ = current_timestamp where CREATION_INFO_DATE_ is null ;
alter table MEDICALRECORD_CONSULTATION_RECORD alter column CREATION_INFO_DATE_ set not null ;
alter table MEDICALRECORD_CONSULTATION_RECORD add column CREATION_INFO_DOCTOR_SURNAME varchar(255) ;
alter table MEDICALRECORD_CONSULTATION_RECORD add column CREATION_INFO_CLINIC_NAME longvarchar ;
