alter table MEDICALRECORD_WEIGHT_MONITORING alter column LOCAL_DATE_TIME rename to LOCAL_DATE_TIME__U94932 ^
alter table MEDICALRECORD_WEIGHT_MONITORING alter column LOCAL_DATE_TIME__U94932 set null ;
alter table MEDICALRECORD_WEIGHT_MONITORING add column LOCAL_DATE_TIME date ^
update MEDICALRECORD_WEIGHT_MONITORING set LOCAL_DATE_TIME = current_date where LOCAL_DATE_TIME is null ;
alter table MEDICALRECORD_WEIGHT_MONITORING alter column LOCAL_DATE_TIME set not null ;
